### ISSUE TITLE
Cast error throws when I use type `yearmonth` in schema

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/tableschema-py#201] opened 2017-12-06 08:16 UTC
```
  File "/usr/local/lib/python3.6/site-packages/tableschema/table.py", line 80, in iter
    for row_number, headers, row in iterator:
  File "/usr/local/lib/python3.6/site-packages/tableschema/table.py", line 189, in builtin_processor
    row = self.__schema.cast_row(row)
  File "/usr/local/lib/python3.6/site-packages/tableschema/schema.py", line 152, in cast_row
    raise exceptions.CastError(message, errors=errors)
tableschema.exceptions.CastError: There are 1 cast errors (see exception.errors)
```
How data looks like:
```
Date,Brent Spot Price
1950-02,34.730
1950-03,34.730
1950-04,34.730
```

Schema: 
```
"schema": {
        "fields": [
          {
            "name": "Date",
            "type": "yearmonth"
          },
          {
            "name": "Brent Spot Price",
            "type": "string"
          }
        ]
      }
```

**Comment by rufuspollock** [comment] 2018-01-16 10:05
@roll any eta on when this will get fixed?

**Comment by roll** [comment] 2018-01-17 08:00
cc @jobarratt

**Comment by vitorbaptista** [comment] 2018-01-18 11:30
@Mikanebu @rufuspollock I just tried this and everything worked fine.

I'll close this issue as I can't reproduce the bug. Please feel free to reopen it if it's still affecting you.

**Closed by vitorbaptista** 2018-01-18 11:30 UTC
Labels: bug, {planning}

**Comment by rufuspollock** [comment] 2018-02-07 02:25
@Mikanebu can you please comment here - apparently the bug is not reproducable.

**Comment by Mikanebu** [comment] 2018-02-07 14:29
@rufuspollock I could not reproduce it using `tableschema-py`. It is throwing error from assembler pointing to tablechame error. We are using latest tableschema version
```
"assembler.load_private_resource: ERROR   :Failed to cast row: Field \"Date\" can't cast value \"[1987, 5]\" for type \"yearmonth\" with format \"default\"",
"assembler.load_private_resource: tableschema.exceptions.CastError: There are 1 cast errors (see exception.errors)"
```

**Comment by rufuspollock** [comment] 2018-02-11 19:04
@vitorbaptista does that help at all? @Mikanebu i think you need to reproduce directly with tableschema-py to be helpful ...
